Can't get caching of build-qt6 to work, so use ccache and cache that.

diff --git a/.github/workflows/build_qtifw.yml b/.github/workflows/build_qtifw.yml
--- a/.github/workflows/build_qtifw.yml
+++ b/.github/workflows/build_qtifw.yml
@@ -34,6 +34,7 @@ jobs:
 
     steps:
     - name: setup
+      id: setup-runner
       shell: bash
       run: |
         sudo xcode-select -switch "${{ matrix.SDKROOT }}"
@@ -47,12 +48,30 @@ jobs:
         mkdir build-qt6
         mkdir build-ifw
 
-    - name: Restore Qt6 cache
-      id: cache-qt6
-      uses: actions/cache/restore@v4
+        export CCACHE_DIR="${{ github.workspace }}/.ccache"
+        echo "CCACHE_DIR=$CCACHE_DIR"
+        echo "CCACHE_DIR=$CCACHE_DIR" >> $GITHUB_ENV
+        echo "ccache-dir=$CCACHE_DIR" >> $GITHUB_OUTPUT
+        ccache --set-config=cache_dir=$CCACHE_DIR
+        ccache --set-config=max_size=2G
+        ccache --set-config=compression=true
+        ccache --set-config=sloppiness=pch_defines,time_macros
+        ccache --set-config=compiler_check=content # darwin only
+        ccache -p
+
+        echo "CMAKE_C_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
+        echo "CMAKE_CXX_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
+
+    - name: Restore CCache cache
+      uses: actions/cache/restore@v5
+      id: cacheccache-restore
       with:
-        path: build-qt6/qtbase
-        key: qt6-6.11.0-a76004f1-${{ matrix.os }}-libarchive-${{ env.USE_LIBARCHIVE }}
+        path: |
+          ${{ steps.setup-runner.outputs.ccache-dir }}
+        key: ccache-qt6-6.11.0-${{ matrix.os }}-libarchive-${{ env.USE_LIBARCHIVE }}-${{ github.run_id }}
+        restore-keys: |
+          ccache-qt6-6.11.0-${{ matrix.os }}-libarchive-${{ env.USE_LIBARCHIVE }}-
+          ccache-qt6-6.11.0-${{ matrix.os }}-
 
     - name: Checkout Qt6 repos
       shell: bash
@@ -70,22 +89,19 @@ jobs:
       working-directory: build-qt6
       shell: bash
       run: |
-        ../qt6/configure -prefix $PWD/qtbase -release -static -accessibility -qt-zlib -qt-libpng -no-cups -no-sql-sqlite -no-qml-debug -nomake examples -nomake tests -no-freetype
+        ../qt6/configure -prefix $PWD/qtbase -release -static -accessibility -qt-zlib -qt-libpng -no-cups -no-sql-sqlite -no-qml-debug -nomake examples -nomake tests -no-freetype \
+          -- -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
 
     - name: Build Qt6 statically
-      if: steps.cache-qt6.outputs.cache-hit != 'true'
       working-directory: build-qt6
       shell: bash
       run: |
+        ccache --zero-stats
         ninja
-        ninja install || true
+        ccache --show-stats
 
-    - name: Save Qt6 cache
-      if: steps.cache-qt6.outputs.cache-hit != 'true'
-      uses: actions/cache/save@v4
-      with:
-        path: build-qt6/qtbase
-        key: ${{ steps.cache-qt6.outputs.cache-primary-key }}
+        echo "Install can't work"
+        ninja install || true
 
     - name: Add Qt6 to PATH
       run: echo "${{ github.workspace }}/build-qt6/qtbase/bin" >> $GITHUB_PATH
@@ -128,6 +144,14 @@ jobs:
         begin_group "Build"
         make -j $(nproc)
         echo "::endgroup::"
+
+    - name: Save CCache cache
+      if: always() && steps.cacheccache-restore.outputs.cache-hit != 'true'
+      uses: actions/cache/save@v5
+      with:
+        path: |
+          ${{ steps.setup-runner.outputs.ccache-dir }}
+        key: ${{ steps.cacheccache-restore.outputs.cache-primary-key }}
 
     - name: Inspect installerbase version
       id: installerbase-version
